dataset_raw_dir: ${hydra:runtime.cwd}/data/runs
interim_path: ${hydra:runtime.cwd}/data/interim
processed_path: ${hydra:runtime.cwd}/data/processed
time_step: 5

section_distances:
  - 7.479
  - 14.312
  - 21.146
  - 27.979
  - 34.812
  - 41.646
  - 48.479
  - 55.312
  - 62.146

hub_height: 90.0