time_steps:
  structural: 0.01

calculated_parameters:
  hub_height: 90.0
  flexible_tower_length: 87.6
  flexible_blade_length: 61.5

rotor_mass_properties:
  rotor_mass: 109668.758
  rotor_inertia: 38687288.000
  blades:
    - blade: 1
      mass: 17629.586
      second_mass_moment: 11754901.000
      first_mass_moment: 362354.312
      center_of_mass: 20.554
    - blade: 2
      mass: 17629.586
      second_mass_moment: 11754901.000
      first_mass_moment: 362354.312
      center_of_mass: 20.554
    - blade: 3
      mass: 17629.586
      second_mass_moment: 11754901.000
      first_mass_moment: 362354.312
      center_of_mass: 20.554

additional_mass_properties:
  tower_top_mass: 349668.750
  tower_mass: 347460.219
  platform_mass: 0.000
  mass_including_platform: 697129.000