header:
  generated_by: "ElastoDyn (v1.04.00a-bjj, 26-Jul-2016)"
  generation_date: "10-Nov-2024"
  generation_time: "23:52:55"

turbine_features:
  description: "Upwind, three-bladed rotor with rigid hub."
  dofs:
    - name: "Platform horizontal surge translation DOF"
      status: "Disabled"
    - name: "Platform horizontal sway translation DOF"
      status: "Disabled"
    - name: "Platform vertical heave translation DOF"
      status: "Disabled"
    - name: "Platform roll tilt rotation DOF"
      status: "Disabled"
    - name: "Platform pitch tilt rotation DOF"
      status: "Disabled"
    - name: "Platform yaw rotation DOF"
      status: "Disabled"
    - name: "1st tower fore-aft bending mode DOF"
      status: "Enabled"
    - name: "1st tower side-to-side bending mode DOF"
      status: "Enabled"
    - name: "2nd tower fore-aft bending mode DOF"
      status: "Enabled"
    - name: "2nd tower side-to-side bending mode DOF"
      status: "Enabled"
    - name: "Nacelle yaw DOF"
      status: "Enabled"
    - name: "Rotor-furl DOF"
      status: "Disabled"
    - name: "Variable speed generator DOF"
      status: "Enabled"
    - name: "Drivetrain rotational-flexibility DOF"
      status: "Enabled"
    - name: "Tail-furl DOF"
      status: "Disabled"
    - name: "1st flapwise bending-mode DOF of blade 1"
      status: "Enabled"
    - name: "1st edgewise bending-mode DOF of blade 1"
      status: "Enabled"
    - name: "2nd flapwise bending-mode DOF of blade 1"
      status: "Enabled"
    - name: "1st flapwise bending-mode DOF of blade 2"
      status: "Enabled"
    - name: "1st edgewise bending-mode DOF of blade 2"
      status: "Enabled"
    - name: "2nd flapwise bending-mode DOF of blade 2"
      status: "Enabled"
    - name: "1st flapwise bending-mode DOF of blade 3"
      status: "Enabled"
    - name: "1st edgewise bending-mode DOF of blade 3"
      status: "Enabled"
    - name: "2nd flapwise bending-mode DOF of blade 3"
      status: "Enabled"

time_steps:
  structural: 0.01

calculated_parameters:
  hub_height: 90.0
  flexible_tower_length: 87.6
  flexible_blade_length: 61.5

rotor_mass_properties:
  rotor_mass: 109668.758
  rotor_inertia: 38687288.000
  blades:
    - blade: 1
      mass: 17629.586
      second_mass_moment: 11754901.000
      first_mass_moment: 362354.312
      center_of_mass: 20.554
    - blade: 2
      mass: 17629.586
      second_mass_moment: 11754901.000
      first_mass_moment: 362354.312
      center_of_mass: 20.554
    - blade: 3
      mass: 17629.586
      second_mass_moment: 11754901.000
      first_mass_moment: 362354.312
      center_of_mass: 20.554

additional_mass_properties:
  tower_top_mass: 349668.750
  tower_mass: 347460.219
  platform_mass: 0.000
  mass_including_platform: 697129.000

model_description: "FAST NREL 5.0 MW Baseline Wind Turbine (Onshore)"
interpolation_order: 2    # quadratic
correction_iterations: 0
